# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies using the Makefile
      - name: Install dependencies using Makefile
        run: make install

      # Step 4: Run the application using the Makefile
      - name: Start the Flask application
        run: |
          make run &
          sleep 10  # Sleep to allow the server time to start

      # Step 5: Verify that the server is running
      - name: Verify the server is running
        run: curl http://localhost:3000 || exit 1
