# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies using the Makefile
      - name: Install dependencies using Makefile
        run: make install

      # Step 4: Run the Flask application and capture logs
      - name: Start the Flask application
        run: |
          make run > flask_server.log 2>&1 &  # Start the server and save logs
          sleep 60                            # Wait 60 seconds for the server to start
          cat flask_server.log                # Display the server log to check for errors
          if ! grep -q "Running on http://0.0.0.0:3000" flask_server.log; then  # Check if the server started correctly
            echo "Error: Flask server did not start correctly."
            exit 1
          fi

      # Step 5: Verify that the server is running
      - name: Verify the server is running
        run: curl http://localhost:3000 || exit 1  # Check if the server is accessible
